---
title: "Errata for _Statistics for Linguists: An Introduction Using R_, Bodo Winter, 2019, Routledge"
author: "| Dan Villarreal \n| University of Pittsburgh\n"
date: "Updated 2/25/2021"
output: 
  html_document:
    toc: yes
    toc_float: yes
---


```{css, include=FALSE}
##Set widths for 1st & 2nd columns
tbody>tr>:nth-child(1) {
  width: 50px;
}
tbody>tr>:nth-child(2) {
  width: 400px;
}

##More space above headings
h1 {
  margin-top: 400px;
}
```

This document contains errata (and non-error important notes) for the textbook _Statistics for Linguists: An Introduction Using R_ (Bodo Winter, 2019, Routledge). Please feel free to suggest other errata by creating a [GitHub issue](https://github.com/djvill/Winter-2019-Errata/issues).


# Chapter 3: Descriptive statistics

|Page|Text|Comment|
|----:|-----|-----|
|53|The corresponding histogram is shown in Figure 3.1a (for an explanation of histograms, see Chapter 1.12).|Figure 3.1a is a barplot, not a histogram.|
|56|(Footnote 2)|This book uses _N_ and _n_ interchangeably (including in this footnote). In other texts, _N_ refers to the size of a population and _n_ to the size of a sample of that population.|
|64|`war <- read_csv(' warriner_2013_emotional_valence.csv')`|There is an extra space after the first quotation mark. This space needs to be removed or else the code will yield an error.|
|65|(Code output at the bottom of the page)|**Content warning:** This code output contains the most negative words in the dataframe, and there are some potentially triggering words in here.|


# Chapter 4: Introduction to the linear model

|    Page    |    Text                                                                   |    Comment                                                                                                                                                                                                         |
|---------------:|-------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|    74      |    E4.7: $y = b_{0} + b_{1} * x + e$    |   The error term is sometimes notated as epsilon ($\epsilon$), but notated as $e$, it shouldn't be confused with the natural logarithm base (also notated $e$), which is discussed in section 5.4.                                                                      |
|    75      |    Figure 4.6 shows the _SSE_ as a function of different slope values.    |    Should be Figure 4.5b, not Figure 4.6                                                                                                                                                                                     |
|    77      |    Conversely, 32% of the variation in response durations is due to chance    |    Should be 28% (100%$-$74%), not 32%.              |
|    78      |    `plot(x., y, pch = 19)`                                               |    Extra dot. Should be<br>`plot(x, y, pch = 19)`                                                                                                                                                                 |
|    81–2    |    `# A tibble: 50 x 2`<br>(...)<br>`# ... with 40 more rows`           |    The preceding code will yield a tibble with 61 rows, not 50. So your output should be<br>`# A tibble: 61 x 2`<br>(...)<br>`# ... with 50 more rows`                                                      |
|    83      |    (Code output starting with `r.squared`)                                  |    The alignment of this output apparently got messed up in the book publication process, but your output should be nicely lined up between the labels (like `r.squared`) and the quantities (like `0.9283634`)    |
|    83      |    The resultant plot will look similar to Figure 4.9                                 |    There is no Figure 4.9! Your plot will look similar to the following (but not identical, because we didn't set a random seed):    |

```{r echo=FALSE}
library(ggplot2)
set.seed(412)
# Generate 50 random numbers:
x <- rnorm(50)
# Create y's with intercept = 10 and slope = 3:
error <- rnorm(50)
y <- 10 + 3 * x + error
mydf <- data.frame(x, y)
ggplot(mydf, aes(x = x, y = y)) +
geom_point() + geom_smooth(method = 'lm', formula=y~x) +
theme_minimal()
```





# Chapter 5: Linear and nonlinear transformations

|    Page    |    Text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |    Comment                                                                         |
|---------------:|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------|
|    92      |    The log~10~ of 1000 is 3, which is a difference of 998 [between the logarithm and the raw number].                                                                                                                                                                                                                                                                                                                                                                                                    |    Should be 997, not 998.                                                         |
|    97      |    (Code output for `tidy(ELP_mdl)`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |    Your output will probably have a lot fewer decimal places.                      |
|    100     |    First, compare `xmdl` to `xmdl_c`. There is no change in the slope, but the intercept is different in the centered model. In both models, the intercept is the prediction for $x$ = 0, but $x$ = 0 corresponds to the average frequency in the centered model. Second, compare `xmdl_c` and `xmdl_z`. The intercepts are the same because, for both models, the predictor has been centered. However, the slope has changed because a change in one unit is now a change in 1 standard deviation.    |    All the instances of `xmdl` should be `ELP_mdl` (including with the `_c` suffix)    |




# Chapter 6: Multiple regression

|    Page    |    Text                                                                                         |    Comment                                                                                                                  |
|---------------:|-----------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------|
|    103     |    E6.1: $y = b_{0} + b_{1} * x + b_{2} * x + e$                                                           |    This equation suggests that $b_{1}$ and $b_{2}$ are multiplied by the same predictor $x$. In the case of multiple regression, each predictor has its own coefficient (as in E6.3, bottom of page), so a more accurate form would be $y = b_{0} + b_{1} * x_{1} + b_{2} * x_{2} + e$   |
|    106     |    (Code output for `tidy(icon_mdl)`)                                                           |    Your output will probably have a lot fewer decimal places.                                                               |
|    106--7  |    Footnote 2 discussion of rounding                                                                                 |    Two points of clarification about rounding: (1) Rounding should only be done at the _end_ of an analysis; any earlier, and you're losing precision in your calculations, running the risk of a rounding error compounding over the course of many calculations. (2) Rounding should only be done when you want to display numbers as numbers, not when feeding numbers into a plot.                                                               |
|    107     |    (Footnote 3) A log frequency of 0 corresponds to a raw word frequency of 1, since 100=1    |    Missing superscript. Should be<br>A log frequency of 0 corresponds to a raw word frequency of 1, since 10^0^=1    |
|    111     |    `for (i in 1:9) plot(rnorm(50), rnorm(50))`                                                  |    If your Plots pane in RStudio is too small, running this code will yield `"Error in plot.new() : figure margins too large".` If so, just make Plots pane wider/taller.                                             |






# Chapter 7: Categorical predictors

|    Page    |    Text                                         |    Comment                                                                                                                                            |
|---------------:|-----------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------|
|    120     |    (Code output at the bottom of the page)    |    In more recent `dplyr` versions, we also get a warning message: <br>```summarise()` ungrouping output (override with `.groups` argument)``    |




# Chapter 8: Interactions and nonlinear effects


|    Page    |    Text                                                                                                                                                                                                 |    Comment                                                                                                                                          |
|---------------:|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------|
|    140     |    `# Groups: Phon, Sem [4]`                                                                                                                                                                            |    Your output should omit this line                                                                                                                |
|    142     |    However, these are not the average row-wise or column-wise differences, as one also has to include the interaction term (highlighted in bold [in Table 8.1]) in calculating these averages.    |    The interaction term isn't bolded in Table 8.1. This is the interaction term that's being referred to:<br>78.4 + 8.0 + (−7.8)+(−4.6)    |





# Chapter 9: Inferential statistics 1


|    Page    |    Text                                                                                                                                                      |    Comment                                                                                                                                                                                                                                                                       |
|---------------:|------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|    161     |    (Figure 9.2)                                                                                                                                   |    According to the equation for Cohen's _d_ (E9.1), the _d_ values in this figure should be 1, 2, and 6                                                                                                                                                                          |
|    162     |    `Cohen's d`<br>`d estimate: 1.037202 (large)`<br>`95 percent confidence interval:`<br>`      inf       sup`<br>`0.5142663 1.5601377`    |    Using the latest version of the `effsize` package (0.8.1), I get the following instead:<br> `Cohen's d`<br>`d estimate: -1.070784 (large)`<br>`95 percent confidence interval:`<br>`     lower      upper `<br>`-1.5955866 -0.5459824`    |


# Chapter 10: Inferential statistics 2

No errata found.




# Chapter 11: Inferential statistics 3


|    Page    |    Text                                                                                                                                                                                 |    Comment                                                                                 |
|---------------:|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------|
|    180     |    (Footnote 1)<br>When _p_-values focus on the SER column are very small numbers                                                                                                |    Typo. Should be:<br>When _p_-values are very small numbers                       |
|    182     |    For the SER predictor, this interval is [0.53−1.96\*0.04, 0.53+1.96\*0.04], which yields the 95% confidence interval [45, 61] (with a little rounding).                            |    The latter confidence interval should be [0.45, 0.61]                                   |
|    191     |    `CI_tib <- mutate(sense_preds,`<br>`                   LB = fits – 1.96 * SEs, # lower bound`<br>`                   UB = fits + 1.96 * SEs)`                                |    `sense_preds` should be `CI_tib.` <br>The 'minus sign' is actually an en dash (–)    |
|    193     |    These mappings assign the y-minimum of the error bar to the lower-bound column from the sense_preds tibble (`LB`), and the y-maximum of the error bar to the upper bound (`UB`)    |    `LB` and `UB` should be `lwr` and `upr`, respectively                                           |
|    194     |    `levels >= sense_order`                                                                                                                                                                |    `>=` should be `=`                                                                          |
|    196     |    (Code output at the top of the page)                                                                                                                                                 |    The `Log10Freq` column shouldn't be duplicated                                            
|    196     |    `geom_ribbon(aes(ymin = LB, ymax = UB),`                                                                                                                                               |    `LB` and `UB` should be `lwr` and `upr`, respectively                                           |




# Chapter 12: Generalized linear models 1

|    Page    |    Text                                                                                                                               |    Comment                                                                                                                                                             |
|---------------:|-------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|    202     |    Even if you supply very extreme values such as 10,000 or –10,000 to `plogis()`, it will always return a number between 0 and 1.    |    In the current version of R (4.0.3), `plogis(17)` returns `1`. While `1 - plogis(17)` is nonzero, `1 - plogis(37)` returns `0`, and `qlogis(1 - plogis(37))` returns `-Inf`.    |